//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.HDBW.Apollo.Client.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("De.HDBW.Apollo.Client.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Kann nur einmalig ausgeführt werden.
        /// </summary>
        public static string AssessmentDescriptionView_OnlyOnce {
            get {
                return ResourceManager.GetString("AssessmentDescriptionView_OnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string AssessmentDescriptionView_Title {
            get {
                return ResourceManager.GetString("AssessmentDescriptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test starten*.
        /// </summary>
        public static string AssessmentDescriptionViewModel_Skill_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_Skill_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test starten*.
        /// </summary>
        public static string AssessmentDescriptionViewModel_SoftSkill_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_SoftSkill_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umfrage starten*.
        /// </summary>
        public static string AssessmentDescriptionViewModel_Survey_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_Survey_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string AssessmentItem_DecoratorText {
            get {
                return ResourceManager.GetString("AssessmentItem_DecoratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string AssessmentResultView_CloseAssessment {
            get {
                return ResourceManager.GetString("AssessmentResultView_CloseAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Rahmen der Testversion zeigen wir dir hier dein vorläufiges Ergebnis. Wie du im Vergleich zu anderen abschneidest, erfährst du in der finalen Version der App!.
        /// </summary>
        public static string AssessmentResultView_Description {
            get {
                return ResourceManager.GetString("AssessmentResultView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Analyse.
        /// </summary>
        public static string AssessmentResultView_Headline {
            get {
                return ResourceManager.GetString("AssessmentResultView_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empfohlene Inhalte.
        /// </summary>
        public static string AssessmentResultView_RecommendationDescription {
            get {
                return ResourceManager.GetString("AssessmentResultView_RecommendationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lerne neue Fähigkeiten.
        /// </summary>
        public static string AssessmentResultView_RecommendationHeadline {
            get {
                return ResourceManager.GetString("AssessmentResultView_RecommendationHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswertung.
        /// </summary>
        public static string AssessmentResultView_Title {
            get {
                return ResourceManager.GetString("AssessmentResultView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lückentext.
        /// </summary>
        public static string AssessmentType_Cloze {
            get {
                return ResourceManager.GetString("AssessmentType_Cloze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahrungen.
        /// </summary>
        public static string AssessmentType_ExperienceAssessment {
            get {
                return ResourceManager.GetString("AssessmentType_ExperienceAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string AssessmentType_SkillAssessment {
            get {
                return ResourceManager.GetString("AssessmentType_SkillAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selbsttest.
        /// </summary>
        public static string AssessmentType_SoftSkillAssessment {
            get {
                return ResourceManager.GetString("AssessmentType_SoftSkillAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umfrage.
        /// </summary>
        public static string AssessmentType_Survey {
            get {
                return ResourceManager.GetString("AssessmentType_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortfahren.
        /// </summary>
        public static string CancelAssessmentDialog_Cancel {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test beenden.
        /// </summary>
        public static string CancelAssessmentDialog_Continue {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests sind nur einmalig durchführbar und können nicht wiederholt werden..
        /// </summary>
        public static string CancelAssessmentDialog_Message {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du dir sicher, dass du den Test beenden möchtest?.
        /// </summary>
        public static string CancelAssessmentDialog_Title {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufserfahrung.
        /// </summary>
        public static string CareerInfoEditView_Title {
            get {
                return ResourceManager.GetString("CareerInfoEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string CompletionState_Completed {
            get {
                return ResourceManager.GetString("CompletionState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string CompletionState_Failed {
            get {
                return ResourceManager.GetString("CompletionState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anerkennung läuft.
        /// </summary>
        public static string CompletionState_Ongoning {
            get {
                return ResourceManager.GetString("CompletionState_Ongoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich stimme zu..
        /// </summary>
        public static string ConfirmDataUsageDialog_Agree {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string ConfirmDataUsageDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string ConfirmDataUsageDialog_Continue {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Ihrer Anmeldung stimmen Sie einer Kontaktaufnahme und Datenspeicherung für die Vorbereitung, Durchführung, Nachbereitung und Dokumentation der Beta zu. Die Anmeldung kann in den Einstellungen der App jeder Zeit wiederrufen werden..
        /// </summary>
        public static string ConfirmDataUsageDialog_Message {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir benötigen Ihre Zustimmung.
        /// </summary>
        public static string ConfirmDataUsageDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktdaten.
        /// </summary>
        public static string ContactInfoEditView_Title {
            get {
                return ResourceManager.GetString("ContactInfoEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulassung.
        /// </summary>
        public static string CourseTagType_Admission {
            get {
                return ResourceManager.GetString("CourseTagType_Admission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilnahmebescheinigung.
        /// </summary>
        public static string CourseTagType_AttendeeCertificate {
            get {
                return ResourceManager.GetString("CourseTagType_AttendeeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zertifikat.
        /// </summary>
        public static string CourseTagType_Certificate {
            get {
                return ResourceManager.GetString("CourseTagType_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterbildung.
        /// </summary>
        public static string CourseTagType_Course {
            get {
                return ResourceManager.GetString("CourseTagType_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung.
        /// </summary>
        public static string CourseTagType_InfoEvent {
            get {
                return ResourceManager.GetString("CourseTagType_InfoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilqualifikation.
        /// </summary>
        public static string CourseTagType_PartialQualification {
            get {
                return ResourceManager.GetString("CourseTagType_PartialQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifikation.
        /// </summary>
        public static string CourseTagType_Qualification {
            get {
                return ResourceManager.GetString("CourseTagType_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string CourseType_All {
            get {
                return ResourceManager.GetString("CourseType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorort.
        /// </summary>
        public static string CourseType_InHouse {
            get {
                return ResourceManager.GetString("CourseType_InHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönlich.
        /// </summary>
        public static string CourseType_InPerson {
            get {
                return ResourceManager.GetString("CourseType_InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online und Vorort.
        /// </summary>
        public static string CourseType_OnAndOffline {
            get {
                return ResourceManager.GetString("CourseType_OnAndOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string CourseType_Online {
            get {
                return ResourceManager.GetString("CourseType_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorteile.
        /// </summary>
        public static string CourseView_Benefits {
            get {
                return ResourceManager.GetString("CourseView_Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansprechpartner.
        /// </summary>
        public static string CourseView_Contact {
            get {
                return ResourceManager.GetString("CourseView_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis.
        /// </summary>
        public static string CourseView_LearningOutcomes {
            get {
                return ResourceManager.GetString("CourseView_LearningOutcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanzierungsoptionen anzeigen.
        /// </summary>
        public static string CourseView_LoanOptions {
            get {
                return ResourceManager.GetString("CourseView_LoanOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voraussetzungen.
        /// </summary>
        public static string CourseView_PreRequisites {
            get {
                return ResourceManager.GetString("CourseView_PreRequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESCO-Skills.
        /// </summary>
        public static string CourseView_Skills {
            get {
                return ResourceManager.GetString("CourseView_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zielgruppe.
        /// </summary>
        public static string CourseView_TargetGroup {
            get {
                return ResourceManager.GetString("CourseView_TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursinformationen.
        /// </summary>
        public static string CourseView_Title {
            get {
                return ResourceManager.GetString("CourseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Anbieter.
        /// </summary>
        public static string CourseView_VisitVendor {
            get {
                return ResourceManager.GetString("CourseView_VisitVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schul- und Berufsbildun.
        /// </summary>
        public static string EducationInfoEditView_Title {
            get {
                return ResourceManager.GetString("EducationInfoEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir unterstützen dich beim Erreichen deiner persönlichen Ziele durch passgenaue Lerninhalte.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entdecke passende Weiterbildungen.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkenne Trends in deinem Berufsfeld und sei immer auf dem neuesten Stand.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halte dein Wissen aktuell.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste dein Wissen und analysiere deine Fähigkeiten.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfalte dein Potential.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zur Beta von Apollo.
        /// </summary>
        public static string ExtendedSplashScreenView_Welcome {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forms.office.com/e/cmES4qec8q.
        /// </summary>
        public static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direkt loslegen.
        /// </summary>
        public static string FirstTimeDialog_Continue {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zum ersten mal hier?.
        /// </summary>
        public static string FirstTimeDialog_Message {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial anzeigen.
        /// </summary>
        public static string FirstTimeDialog_OpenTutorial {
            get {
                return ResourceManager.GetString("FirstTimeDialog_OpenTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen!.
        /// </summary>
        public static string FirstTimeDialog_Title {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Global_Back {
            get {
                return ResourceManager.GetString("Global_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadt.
        /// </summary>
        public static string Global_City {
            get {
                return ResourceManager.GetString("Global_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string Global_Close {
            get {
                return ResourceManager.GetString("Global_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anerkannt.
        /// </summary>
        public static string Global_CompletionState {
            get {
                return ResourceManager.GetString("Global_CompletionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Global_Country {
            get {
                return ResourceManager.GetString("Global_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Global_Discribtion {
            get {
                return ResourceManager.GetString("Global_Discribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minuten.
        /// </summary>
        public static string Global_DurationFormat {
            get {
                return ResourceManager.GetString("Global_DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Stunden.
        /// </summary>
        public static string Global_DurationFormatHours {
            get {
                return ResourceManager.GetString("Global_DurationFormatHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende.
        /// </summary>
        public static string Global_End {
            get {
                return ResourceManager.GetString("Global_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string Global_NameOfInstitution {
            get {
                return ResourceManager.GetString("Global_NameOfInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Global_Next {
            get {
                return ResourceManager.GetString("Global_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsbezeichnung.
        /// </summary>
        public static string Global_Occupation {
            get {
                return ResourceManager.GetString("Global_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schulabschluss.
        /// </summary>
        public static string Global_SchoolGraduation {
            get {
                return ResourceManager.GetString("Global_SchoolGraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstart.
        /// </summary>
        public static string Global_ServiceType {
            get {
                return ResourceManager.GetString("Global_ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        public static string Global_Skip {
            get {
                return ResourceManager.GetString("Global_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Global_Start {
            get {
                return ResourceManager.GetString("Global_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt starten.
        /// </summary>
        public static string Global_StartNow {
            get {
                return ResourceManager.GetString("Global_StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schulart.
        /// </summary>
        public static string Global_TypeOfSchool {
            get {
                return ResourceManager.GetString("Global_TypeOfSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochschulabschluss.
        /// </summary>
        public static string Global_UniverityDegree {
            get {
                return ResourceManager.GetString("Global_UniverityDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitszeitmodel.
        /// </summary>
        public static string Global_WorkTimeModel {
            get {
                return ResourceManager.GetString("Global_WorkTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trifft garnicht zu.
        /// </summary>
        public static string IntegerInput_Negative {
            get {
                return ResourceManager.GetString("IntegerInput_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trifft voll zu.
        /// </summary>
        public static string IntegerInput_Positive {
            get {
                return ResourceManager.GetString("IntegerInput_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachkenntnisse.
        /// </summary>
        public static string LanguageSkillEditView_Title {
            get {
                return ResourceManager.GetString("LanguageSkillEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenzen und Berechtigungen.
        /// </summary>
        public static string LicenseEditView_Title {
            get {
                return ResourceManager.GetString("LicenseEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zukünftig werden dir hier weitere Funktionen zur Verfügung stehen.
        /// </summary>
        public static string MainNavigation_BetaDescription {
            get {
                return ResourceManager.GetString("MainNavigation_BetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Version.
        /// </summary>
        public static string MainNavigation_BetaTitle {
            get {
                return ResourceManager.GetString("MainNavigation_BetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeugnisse und Abschlüsse.
        /// </summary>
        public static string MainNavigation_CertificatesAndDegrees {
            get {
                return ResourceManager.GetString("MainNavigation_CertificatesAndDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szenario wechseln.
        /// </summary>
        public static string MainNavigation_ChangeUseCase {
            get {
                return ResourceManager.GetString("MainNavigation_ChangeUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gemerkte Kurse.
        /// </summary>
        public static string MainNavigation_CoursesFavorites {
            get {
                return ResourceManager.GetString("MainNavigation_CoursesFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Generator.
        /// </summary>
        public static string MainNavigation_CVGenerator {
            get {
                return ResourceManager.GetString("MainNavigation_CVGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil bearbeiten.
        /// </summary>
        public static string MainNavigation_EditProfile {
            get {
                return ResourceManager.GetString("MainNavigation_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback senden.
        /// </summary>
        public static string MainNavigation_Feedback {
            get {
                return ResourceManager.GetString("MainNavigation_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessenfelder.
        /// </summary>
        public static string MainNavigation_FieldsOfInterest {
            get {
                return ResourceManager.GetString("MainNavigation_FieldsOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lernpfad.
        /// </summary>
        public static string MainNavigation_LearningPath {
            get {
                return ResourceManager.GetString("MainNavigation_LearningPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string MainNavigation_Settings {
            get {
                return ResourceManager.GetString("MainNavigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen &amp; Filter.
        /// </summary>
        public static string MainNavigation_SettingsAndFilter {
            get {
                return ResourceManager.GetString("MainNavigation_SettingsAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills &amp; Badges.
        /// </summary>
        public static string MainNavigation_SkillsAndBadges {
            get {
                return ResourceManager.GetString("MainNavigation_SkillsAndBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial anzeigen.
        /// </summary>
        public static string MainNavigation_ViewTutorial {
            get {
                return ResourceManager.GetString("MainNavigation_ViewTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führerscheine.
        /// </summary>
        public static string MobilityEditView_DriverLicenses {
            get {
                return ResourceManager.GetString("MobilityEditView_DriverLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilität.
        /// </summary>
        public static string MobilityEditView_Title {
            get {
                return ResourceManager.GetString("MobilityEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenes Fahrzeug.
        /// </summary>
        public static string MobilityEditView_Vehicle {
            get {
                return ResourceManager.GetString("MobilityEditView_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reisebereitschaft.
        /// </summary>
        public static string MobilityEditView_Willing {
            get {
                return ResourceManager.GetString("MobilityEditView_Willing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollzeit.
        /// </summary>
        public static string OccurrenceType_FullTime {
            get {
                return ResourceManager.GetString("OccurrenceType_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voll- und Teilzeit.
        /// </summary>
        public static string OccurrenceType_FullTimeAndPartTime {
            get {
                return ResourceManager.GetString("OccurrenceType_FullTimeAndPartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilzeit.
        /// </summary>
        public static string OccurrenceType_PartTime {
            get {
                return ResourceManager.GetString("OccurrenceType_PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtstag.
        /// </summary>
        public static string PersonalInformationEditView_Birthdate {
            get {
                return ResourceManager.GetString("PersonalInformationEditView_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkungen.
        /// </summary>
        public static string PersonalInformationEditView_Handicaps {
            get {
                return ResourceManager.GetString("PersonalInformationEditView_Handicaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persöhnliche Informationen.
        /// </summary>
        public static string PersonalInformationEditView_Title {
            get {
                return ResourceManager.GetString("PersonalInformationEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PersonalInformationEditView_UserName {
            get {
                return ResourceManager.GetString("PersonalInformationEditView_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzernamen eingeben.
        /// </summary>
        public static string PersonalInformationEditView_UserNameHint {
            get {
                return ResourceManager.GetString("PersonalInformationEditView_UserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string ProfileView_Title {
            get {
                return ResourceManager.GetString("ProfileView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifikationen.
        /// </summary>
        public static string QualificationEditView_Title {
            get {
                return ResourceManager.GetString("QualificationEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohne Anmeldung fortfahren.
        /// </summary>
        public static string RegistrationView_Continue {
            get {
                return ResourceManager.GetString("RegistrationView_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Während der Testung benötigst Du keine Registrierung/Anmeldung. Wenn Du Dich allerdings für zukünftige Testversionen registrieren möchtest, kannst Du das über &quot;Jetzt anmelden&quot; vornehmen. Solltest Du Deine Meinung ändern, kannst Du über Einstellungen → &quot;Benutzer abmelden&quot; die Registrierung/Anmeldung löschen..
        /// </summary>
        public static string RegistrationView_Description {
            get {
                return ResourceManager.GetString("RegistrationView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt Anmelden.
        /// </summary>
        public static string RegistrationView_RegisterNow {
            get {
                return ResourceManager.GetString("RegistrationView_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt anmelden.
        /// </summary>
        public static string RegistrationView_RegisterUser {
            get {
                return ResourceManager.GetString("RegistrationView_RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string RegistrationView_UnRegisterUser {
            get {
                return ResourceManager.GetString("RegistrationView_UnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachhochschulreife.
        /// </summary>
        public static string SchoolGraduation_AdvancedTechnicalCollegeCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_AdvancedTechnicalCollegeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgänger Klasse 11-13 ohne Abschluss.
        /// </summary>
        public static string SchoolGraduation_AdvancedTechnicalCollegeWithoutCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_AdvancedTechnicalCollegeWithoutCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifizierender / erweiterter Hauptschulabschluss.
        /// </summary>
        public static string SchoolGraduation_ExtendedSecondarySchoolLeavingCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_ExtendedSecondarySchoolLeavingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeine Hochschulreife.
        /// </summary>
        public static string SchoolGraduation_HigherEducationEntranceQualificationALevel {
            get {
                return ResourceManager.GetString("SchoolGraduation_HigherEducationEntranceQualificationALevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittlere Reife / Mittlerer Bildungsabschluss.
        /// </summary>
        public static string SchoolGraduation_IntermediateSchoolCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_IntermediateSchoolCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kein Schulabschluss.
        /// </summary>
        public static string SchoolGraduation_NoSchoolLeavingCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_NoSchoolLeavingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptschulabschluss.
        /// </summary>
        public static string SchoolGraduation_SecondarySchoolCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_SecondarySchoolCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schulabschluss der Förderschule.
        /// </summary>
        public static string SchoolGraduation_SpecialSchoolLeavingCertificate {
            get {
                return ResourceManager.GetString("SchoolGraduation_SpecialSchoolLeavingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachgebundene Hochschulreife.
        /// </summary>
        public static string SchoolGraduation_SubjectRelatedEntranceQualification {
            get {
                return ResourceManager.GetString("SchoolGraduation_SubjectRelatedEntranceQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string SelectOptionDialog_Cancel {
            get {
                return ResourceManager.GetString("SelectOptionDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string SelectOptionDialog_Continue {
            get {
                return ResourceManager.GetString("SelectOptionDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle.
        /// </summary>
        public static string SelectOptionDialog_Title {
            get {
                return ResourceManager.GetString("SelectOptionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinnützige Arbeit.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_CommunityService {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_CommunityService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Außerberufliche Erfahrungen.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_ExtraOccupationalExperience {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_ExtraOccupationalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausfrau/mann.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_Homemaker {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_Homemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_Internship {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_Internship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wehrdienst/-übung/Zivildienst.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_MilitaryService {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_MilitaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstiges.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_Other {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutterschutz / Elternzeit.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_ParentalLeave {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_ParentalLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufspraxis (Nebenbeschäftigung).
        /// </summary>
        public static string SelectOptionsDialog_CareerType_PartTimeWorkExperience {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_PartTimeWorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betr. pflegebed. Person.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_PersonCare {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_PersonCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selbständigkeit.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_SelfEmployment {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_SelfEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilligendienst.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_VoluntaryService {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_VoluntaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufspraxis.
        /// </summary>
        public static string SelectOptionsDialog_CareerType_WorkExperience {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_CareerType_WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsausbildung (betr./außerbetr.).
        /// </summary>
        public static string SelectOptionsDialog_EducationType_CompanyBasedVocationalTraining {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_EducationType_CompanyBasedVocationalTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schulbildung.
        /// </summary>
        public static string SelectOptionsDialog_EducationType_Education {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_EducationType_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterbildung.
        /// </summary>
        public static string SelectOptionsDialog_EducationType_FurtherEducation {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_EducationType_FurtherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studium.
        /// </summary>
        public static string SelectOptionsDialog_EducationType_Study {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_EducationType_Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsausbildung (schulisch).
        /// </summary>
        public static string SelectOptionsDialog_EducationType_VocationalTraining {
            get {
                return ResourceManager.GetString("SelectOptionsDialog_EducationType_VocationalTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zivildienst.
        /// </summary>
        public static string ServiceType_CivilianService {
            get {
                return ResourceManager.GetString("ServiceType_CivilianService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wehrübung.
        /// </summary>
        public static string ServiceType_MilitaryExercise {
            get {
                return ResourceManager.GetString("ServiceType_MilitaryExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grundwehrdienst.
        /// </summary>
        public static string ServiceType_MilitaryService {
            get {
                return ResourceManager.GetString("ServiceType_MilitaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliger Wehrdienst.
        /// </summary>
        public static string ServiceType_VoluntaryMilitaryService {
            get {
                return ResourceManager.GetString("ServiceType_VoluntaryMilitaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo Apollo-Team.
        ///.
        /// </summary>
        public static string SettingsView_EmailBody {
            get {
                return ResourceManager.GetString("SettingsView_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anregungen oder Wunsch zu Apollo.
        /// </summary>
        public static string SettingsView_EmailSubject {
            get {
                return ResourceManager.GetString("SettingsView_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string SettingsView_Imprint {
            get {
                return ResourceManager.GetString("SettingsView_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.invite-apollo.app/Imprint.
        /// </summary>
        public static string SettingsView_ImprintUri {
            get {
                return ResourceManager.GetString("SettingsView_ImprintUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        public static string SettingsView_Privacy {
            get {
                return ResourceManager.GetString("SettingsView_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.invite-apollo.app/privacy.
        /// </summary>
        public static string SettingsView_PrivacyUri {
            get {
                return ResourceManager.GetString("SettingsView_PrivacyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilf uns die Zukunft der Bildung zu gestalten..
        /// </summary>
        public static string SettingsView_QuestionDescription {
            get {
                return ResourceManager.GetString("SettingsView_QuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apollodev@hdbw-hochschule.de.
        /// </summary>
        public static string SettingsView_QuestionEmail {
            get {
                return ResourceManager.GetString("SettingsView_QuestionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anregungen oder Wünsche?.
        /// </summary>
        public static string SettingsView_Questions {
            get {
                return ResourceManager.GetString("SettingsView_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        public static string SettingsView_Terms {
            get {
                return ResourceManager.GetString("SettingsView_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.invite-apollo.app/terms.
        /// </summary>
        public static string SettingsView_TermsUri {
            get {
                return ResourceManager.GetString("SettingsView_TermsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwort wählen.
        /// </summary>
        public static string SkipQuestionDialog_Cancel {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        public static string SkipQuestionDialog_Continue {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jede Frage ist nur einmalig durchführbar und Antworten können nicht korrigiert werden.
        /// </summary>
        public static string SkipQuestionDialog_Message {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du dir sicher, dass du diese Frage überspringen möchtest?.
        /// </summary>
        public static string SkipQuestionDialog_Title {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usecase ändern.
        /// </summary>
        public static string StartView_ChangeUseCase {
            get {
                return ResourceManager.GetString("StartView_ChangeUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Ziel.
        /// </summary>
        public static string StartView_Goal {
            get {
                return ResourceManager.GetString("StartView_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobald du Inhalte favorisierst werden sie hier erscheinen..
        /// </summary>
        public static string StartView_NoFavoritesDescription {
            get {
                return ResourceManager.GetString("StartView_NoFavoritesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast noch keine Favoriten gesetzt.
        /// </summary>
        public static string StartView_NoFavoritesTitle {
            get {
                return ResourceManager.GetString("StartView_NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreiche deine Ziele.
        /// </summary>
        public static string StartViewModel_FavoritesHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_FavoritesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Favoriten.
        /// </summary>
        public static string StartViewModel_FavoritesSubline {
            get {
                return ResourceManager.GetString("StartViewModel_FavoritesSubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entdecke dein Karrierepotential
        ///(Ist-Stand bekannt – Inspiration).
        /// </summary>
        public static string StartViewModel_InteractionCareer {
            get {
                return ResourceManager.GetString("StartViewModel_InteractionCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobald du Inhalte favorisierst werden sie hier erscheinen..
        /// </summary>
        public static string StartViewModel_NoFavoritesText {
            get {
                return ResourceManager.GetString("StartViewModel_NoFavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast noch keine Favoriten gesetzt.
        /// </summary>
        public static string StartViewModel_NoFavoritesTitle {
            get {
                return ResourceManager.GetString("StartViewModel_NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empfohlene Inhalte.
        /// </summary>
        public static string StartViewModel_RecomondationsSubline {
            get {
                return ResourceManager.GetString("StartViewModel_RecomondationsSubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Anbieter.
        /// </summary>
        public static string StartViewModel_UnknownProvider {
            get {
                return ResourceManager.GetString("StartViewModel_UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhöhe deine Jobchancen.
        /// </summary>
        public static string StartViewModel_UseCaseA_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseA_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lerne neue Fähigkeiten.
        /// </summary>
        public static string StartViewModel_UseCaseB_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseB_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschleunige deinen Aufstieg.
        /// </summary>
        public static string StartViewModel_UseCaseC_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseC_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Szenario.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolleg.
        /// </summary>
        public static string TypeOfSchool_Colleague {
            get {
                return ResourceManager.GetString("TypeOfSchool_Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abendgymnasium.
        /// </summary>
        public static string TypeOfSchool_EveningHighSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_EveningHighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abendhauptschule.
        /// </summary>
        public static string TypeOfSchool_EveningSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_EveningSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gymnasium.
        /// </summary>
        public static string TypeOfSchool_HighSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrierte Gesamtschule.
        /// </summary>
        public static string TypeOfSchool_IntegratedComprehensiveSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_IntegratedComprehensiveSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptschule.
        /// </summary>
        public static string TypeOfSchool_MainSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_MainSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abendrealschule.
        /// </summary>
        public static string TypeOfSchool_NightSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_NightSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstige Schule.
        /// </summary>
        public static string TypeOfSchool_Other {
            get {
                return ResourceManager.GetString("TypeOfSchool_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schulart mit mehreren Bildungsgängen.
        /// </summary>
        public static string TypeOfSchool_SchoolWithMultipleCourses {
            get {
                return ResourceManager.GetString("TypeOfSchool_SchoolWithMultipleCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realschule.
        /// </summary>
        public static string TypeOfSchool_SecondarySchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_SecondarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förderschule.
        /// </summary>
        public static string TypeOfSchool_SpecialSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_SpecialSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachakademie.
        /// </summary>
        public static string TypeOfSchool_TechnicalAcademy {
            get {
                return ResourceManager.GetString("TypeOfSchool_TechnicalAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachoberschule.
        /// </summary>
        public static string TypeOfSchool_TechnicalCollege {
            get {
                return ResourceManager.GetString("TypeOfSchool_TechnicalCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachgymnasium.
        /// </summary>
        public static string TypeOfSchool_TechnicalHighSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_TechnicalHighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachschule.
        /// </summary>
        public static string TypeOfSchool_TechnicalSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_TechnicalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochschule.
        /// </summary>
        public static string TypeOfSchool_UniversityOfAppliedScience {
            get {
                return ResourceManager.GetString("TypeOfSchool_UniversityOfAppliedScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsfachschule.
        /// </summary>
        public static string TypeOfSchool_VocationalCollege {
            get {
                return ResourceManager.GetString("TypeOfSchool_VocationalCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsoberschule/ Technische Oberschule.
        /// </summary>
        public static string TypeOfSchool_VocationalHighSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_VocationalHighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsschule.
        /// </summary>
        public static string TypeOfSchool_VocationalSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_VocationalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufsaufbauschule.
        /// </summary>
        public static string TypeOfSchool_VocationalTrainingSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_VocationalTrainingSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freie Waldorfschule.
        /// </summary>
        public static string TypeOfSchool_WaldorfSchool {
            get {
                return ResourceManager.GetString("TypeOfSchool_WaldorfSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor.
        /// </summary>
        public static string UniversityDegree_Bachelor {
            get {
                return ResourceManager.GetString("UniversityDegree_Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string UniversityDegree_Doctorate {
            get {
                return ResourceManager.GetString("UniversityDegree_Doctorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirchliches Examen.
        /// </summary>
        public static string UniversityDegree_EcclesiasticalExam {
            get {
                return ResourceManager.GetString("UniversityDegree_EcclesiasticalExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master / Diplom / Magister.
        /// </summary>
        public static string UniversityDegree_Master {
            get {
                return ResourceManager.GetString("UniversityDegree_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht relevant.
        /// </summary>
        public static string UniversityDegree_Other {
            get {
                return ResourceManager.GetString("UniversityDegree_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilweise anerkannter Abschluss.
        /// </summary>
        public static string UniversityDegree_PartialRecognized {
            get {
                return ResourceManager.GetString("UniversityDegree_PartialRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anerkennung des Abschlusses wird geprüft.
        /// </summary>
        public static string UniversityDegree_Pending {
            get {
                return ResourceManager.GetString("UniversityDegree_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglementierter und nicht anerkannter Abschluss.
        /// </summary>
        public static string UniversityDegree_RegulatedUnrecognized {
            get {
                return ResourceManager.GetString("UniversityDegree_RegulatedUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staatsexamen.
        /// </summary>
        public static string UniversityDegree_StateExam {
            get {
                return ResourceManager.GetString("UniversityDegree_StateExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht reglementierter, nicht anerkannter Abschluss.
        /// </summary>
        public static string UniversityDegree_UnregulatedUnrecognized {
            get {
                return ResourceManager.GetString("UniversityDegree_UnregulatedUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du möchtest dich auf einen sicheren Job vorbereiten.
        /// </summary>
        public static string UseCase_A_Description {
            get {
                return ResourceManager.GetString("UseCase_A_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit für den Job.
        /// </summary>
        public static string UseCase_A_Name {
            get {
                return ResourceManager.GetString("UseCase_A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du möchtest neue Fähigkeiten erwerben.
        /// </summary>
        public static string UseCase_B_Description {
            get {
                return ResourceManager.GetString("UseCase_B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterbildung.
        /// </summary>
        public static string UseCase_B_Name {
            get {
                return ResourceManager.GetString("UseCase_B_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du möchtest in deinem Job Karriere machen.
        /// </summary>
        public static string UseCase_C_Description {
            get {
                return ResourceManager.GetString("UseCase_C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karriereaufstieg.
        /// </summary>
        public static string UseCase_C_Name {
            get {
                return ResourceManager.GetString("UseCase_C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finde passende Kurse für deine Interessen.
        /// </summary>
        public static string UseCase_D_Description {
            get {
                return ResourceManager.GetString("UseCase_D_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        public static string UseCase_D_Name {
            get {
                return ResourceManager.GetString("UseCase_D_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter: {0}.
        /// </summary>
        public static string UseCaseDescriptionView_AgeFormat {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_AgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahrung.
        /// </summary>
        public static string UseCaseDescriptionView_Experience {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel.
        /// </summary>
        public static string UseCaseDescriptionView_Goal {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort: {0}.
        /// </summary>
        public static string UseCaseDescriptionView_LocationFormat {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_LocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szenario starten.
        /// </summary>
        public static string UseCaseDescriptionView_Start {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string UseCaseDescriptionView_Story {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Szenario.
        /// </summary>
        public static string UseCaseDescriptionView_Title {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string UseCaseDetail_A_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Jahre Lager und Kommissionierung
        ///1 Jahr Einzelhandel im Lebensmittelbereich.
        /// </summary>
        public static string UseCaseDetail_A_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job im Bereich Lager
        ///Langfristig stabilere Arbeitsbedingungen.
        /// </summary>
        public static string UseCaseDetail_A_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ludwigsburg.
        /// </summary>
        public static string UseCaseDetail_A_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast in den letzten vier Jahren in einem großen Versandlager gearbeitet. Deine Aufgabe war es, Waren aus dem Lager für Lieferaufträge zusammenzustellen. Vorher hast du eine Ausbildung im Einzelhandel angefangen, jedoch abgebrochen. Dein Unternehmen hat beschlossen, den Standort zu schließen. Du bist auf der Suche nach einem neuen Job im Bereich Lager..
        /// </summary>
        public static string UseCaseDetail_A_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string UseCaseDetail_B_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Jahre Ausbildung Kauffrau im Einzelhandel
        ///19 Jahre Erfahrung im Einzelhandel.
        /// </summary>
        public static string UseCaseDetail_B_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterbildung im Bereich E-Commerce
        ///Anschlussfähig bleiben und neue Bereiche entdecken.
        /// </summary>
        public static string UseCaseDetail_B_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to München.
        /// </summary>
        public static string UseCaseDetail_B_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du arbeitest seit 22 Jahren im Einzelhandel. Dein Betrieb hat in den letzten Jahren neben dem Geschäft vor Ort auch den Online-Handel weiter ausgebaut. Um anschlussfähig zu bleiben, möchtest du dich im Bereich E-Commerce weiterbilden..
        /// </summary>
        public static string UseCaseDetail_B_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string UseCaseDetail_C_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Jahre Ausbildung Fachinformatikerin
        ///1 Jahr Weiterbildung IHK Techniker IT
        ///10 Jahre Erfahrung Systemintegration.
        /// </summary>
        public static string UseCaseDetail_C_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufliche Weiterentwicklung
        ///Weiterbildung zur IT Projektleiterin.
        /// </summary>
        public static string UseCaseDetail_C_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augsburg.
        /// </summary>
        public static string UseCaseDetail_C_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast zehn Jahre Erfahrung als Fachinformatikerin. Neben deiner Arbeit hast du verschiedene Möglichkeiten wahrgenommen, um dich weiterzubilden und auf dem Laufenden zu bleiben. Nun willst du den nächsten Schritt in deiner Karriere gehen. Du bist auf der Suche nach einer Qualifizierung, um eine Führungsposition zu übernehmen..
        /// </summary>
        public static string UseCaseDetail_C_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle Deinen Testbereich.
        /// </summary>
        public static string UseCaseSelectionView_Choose {
            get {
                return ResourceManager.GetString("UseCaseSelectionView_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APOLLO befindet sich noch in der Testphase. Deine Teilnahme hilft uns die App weiterzuentwickeln..
        /// </summary>
        public static string UseCaseSelectionView_ChooseDescription {
            get {
                return ResourceManager.GetString("UseCaseSelectionView_ChooseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundesfreiwilligendienst.
        /// </summary>
        public static string VoluntaryServiceType_FederalVolunteerService {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_FederalVolunteerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstiges.
        /// </summary>
        public static string VoluntaryServiceType_Other {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliges Kulturelles Jahr (FKJ).
        /// </summary>
        public static string VoluntaryServiceType_VoluntaryCulturalYear {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_VoluntaryCulturalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliges Ökologisches Jahr (FÖJ).
        /// </summary>
        public static string VoluntaryServiceType_VoluntaryEcologicalYear {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_VoluntaryEcologicalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliges Soziales Trainingsjahr (FSTJ).
        /// </summary>
        public static string VoluntaryServiceType_VoluntarySocialTrainingYear {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_VoluntarySocialTrainingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliges Soziales Jahr (FSJ).
        /// </summary>
        public static string VoluntaryServiceType_VoluntarySocialYear {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_VoluntarySocialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliges Soziales Jahr im Sport.
        /// </summary>
        public static string VoluntaryServiceType_VoluntarySocialYearInSport {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_VoluntarySocialYearInSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freiwilliges Jahr in der Denkmalpflege (FJD).
        /// </summary>
        public static string VoluntaryServiceType_VoluntaryYearInMonumentConservation {
            get {
                return ResourceManager.GetString("VoluntaryServiceType_VoluntaryYearInMonumentConservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webprofile.
        /// </summary>
        public static string WebReferenceEditView_Title {
            get {
                return ResourceManager.GetString("WebReferenceEditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollzeit.
        /// </summary>
        public static string WorkingTimeModel_FullTime {
            get {
                return ResourceManager.GetString("WorkingTimeModel_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeoffice.
        /// </summary>
        public static string WorkingTimeModel_HomeTeleWork {
            get {
                return ResourceManager.GetString("WorkingTimeModel_HomeTeleWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minijob.
        /// </summary>
        public static string WorkingTimeModel_Minijob {
            get {
                return ResourceManager.GetString("WorkingTimeModel_Minijob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilzeit.
        /// </summary>
        public static string WorkingTimeModel_PartTime {
            get {
                return ResourceManager.GetString("WorkingTimeModel_PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schicht-/Nacht-/Wochenendarbeit.
        /// </summary>
        public static string WorkingTimeModel_ShiftNightWorkWeekend {
            get {
                return ResourceManager.GetString("WorkingTimeModel_ShiftNightWorkWeekend", resourceCulture);
            }
        }
    }
}
