//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.HDBW.Apollo.Client.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("De.HDBW.Apollo.Client.Resources.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Kann nur einmalig ausgeführt werden.
        /// </summary>
        public static string AssessmentDescriptionView_OnlyOnce {
            get {
                return ResourceManager.GetString("AssessmentDescriptionView_OnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string AssessmentDescriptionView_Title {
            get {
                return ResourceManager.GetString("AssessmentDescriptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test starten*.
        /// </summary>
        public static string AssessmentDescriptionViewModel_Skill_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_Skill_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test starten*.
        /// </summary>
        public static string AssessmentDescriptionViewModel_SoftSkill_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_SoftSkill_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umfrage starten*.
        /// </summary>
        public static string AssessmentDescriptionViewModel_Survey_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_Survey_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string AssessmentItem_DecoratorText {
            get {
                return ResourceManager.GetString("AssessmentItem_DecoratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string AssessmentResultView_CloseAssessment {
            get {
                return ResourceManager.GetString("AssessmentResultView_CloseAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswertung.
        /// </summary>
        public static string AssessmentResultView_Title {
            get {
                return ResourceManager.GetString("AssessmentResultView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortfahren.
        /// </summary>
        public static string CancelAssessmentDialog_Cancel {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test beenden.
        /// </summary>
        public static string CancelAssessmentDialog_Continue {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests sind nur einmalig durchführbar und können nicht wiederholt werden..
        /// </summary>
        public static string CancelAssessmentDialog_Message {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du dir sicher, dass du den Test beenden möchtest?.
        /// </summary>
        public static string CancelAssessmentDialog_Title {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulassung.
        /// </summary>
        public static string CourseTagType_Admission {
            get {
                return ResourceManager.GetString("CourseTagType_Admission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilnahmebescheinigung.
        /// </summary>
        public static string CourseTagType_AttendeeCertificate {
            get {
                return ResourceManager.GetString("CourseTagType_AttendeeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zertifikat.
        /// </summary>
        public static string CourseTagType_Certificate {
            get {
                return ResourceManager.GetString("CourseTagType_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string CourseTagType_Course {
            get {
                return ResourceManager.GetString("CourseTagType_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veranstaltung.
        /// </summary>
        public static string CourseTagType_InfoEvent {
            get {
                return ResourceManager.GetString("CourseTagType_InfoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilqualifikation.
        /// </summary>
        public static string CourseTagType_PartialQualification {
            get {
                return ResourceManager.GetString("CourseTagType_PartialQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifikation.
        /// </summary>
        public static string CourseTagType_Qualification {
            get {
                return ResourceManager.GetString("CourseTagType_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir unterstützen dich beim Erreichen deiner persönlichen Ziele durch passgenaue Lerninhalte.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entdecke passende Weiterbildungen.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkenne Trends in deinem Berufsfeld und sei immer auf dem neuesten Stand.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halte dein Wissen aktuell.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste dein Wissen und analysiere deine Fähigkeiten.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfalte dein Potential.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zur Beta von Apollo.
        /// </summary>
        public static string ExtendedSplashScreenView_Welcome {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackView_Title {
            get {
                return ResourceManager.GetString("FeedbackView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direkt loslegen.
        /// </summary>
        public static string FirstTimeDialog_Continue {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zum ersten mal hier?.
        /// </summary>
        public static string FirstTimeDialog_Message {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial anzeigen.
        /// </summary>
        public static string FirstTimeDialog_OpenTutorial {
            get {
                return ResourceManager.GetString("FirstTimeDialog_OpenTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen!.
        /// </summary>
        public static string FirstTimeDialog_Title {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Global_Back {
            get {
                return ResourceManager.GetString("Global_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minuten.
        /// </summary>
        public static string Global_DurationFormat {
            get {
                return ResourceManager.GetString("Global_DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        public static string Global_Skip {
            get {
                return ResourceManager.GetString("Global_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt starten.
        /// </summary>
        public static string Global_StartNow {
            get {
                return ResourceManager.GetString("Global_StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zukünftig werden dir hier weitere Funktionen zur Verfügung stehen.
        /// </summary>
        public static string MainNavigation_BetaDescription {
            get {
                return ResourceManager.GetString("MainNavigation_BetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Version.
        /// </summary>
        public static string MainNavigation_BetaTitle {
            get {
                return ResourceManager.GetString("MainNavigation_BetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeugnisse und Abschlüsse.
        /// </summary>
        public static string MainNavigation_CertificatesAndDegrees {
            get {
                return ResourceManager.GetString("MainNavigation_CertificatesAndDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szenario wechseln.
        /// </summary>
        public static string MainNavigation_ChangeUseCase {
            get {
                return ResourceManager.GetString("MainNavigation_ChangeUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gemerkte Kurse.
        /// </summary>
        public static string MainNavigation_CoursesFavorites {
            get {
                return ResourceManager.GetString("MainNavigation_CoursesFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Generator.
        /// </summary>
        public static string MainNavigation_CVGenerator {
            get {
                return ResourceManager.GetString("MainNavigation_CVGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil bearbeiten.
        /// </summary>
        public static string MainNavigation_EditProfile {
            get {
                return ResourceManager.GetString("MainNavigation_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback senden.
        /// </summary>
        public static string MainNavigation_Feedback {
            get {
                return ResourceManager.GetString("MainNavigation_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessenfelder.
        /// </summary>
        public static string MainNavigation_FieldsOfInterest {
            get {
                return ResourceManager.GetString("MainNavigation_FieldsOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lernpfad.
        /// </summary>
        public static string MainNavigation_LearningPath {
            get {
                return ResourceManager.GetString("MainNavigation_LearningPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string MainNavigation_Settings {
            get {
                return ResourceManager.GetString("MainNavigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen &amp; Filter.
        /// </summary>
        public static string MainNavigation_SettingsAndFilter {
            get {
                return ResourceManager.GetString("MainNavigation_SettingsAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills &amp; Badges.
        /// </summary>
        public static string MainNavigation_SkillsAndBadges {
            get {
                return ResourceManager.GetString("MainNavigation_SkillsAndBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial anzeigen.
        /// </summary>
        public static string MainNavigation_ViewTutorial {
            get {
                return ResourceManager.GetString("MainNavigation_ViewTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohne Anmeldung fortfahren.
        /// </summary>
        public static string RegistrationView_Continue {
            get {
                return ResourceManager.GetString("RegistrationView_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius eu tristique tristique ut. Morbi viverra in tempor maecenas ullamcorper tellus risus eu..
        /// </summary>
        public static string RegistrationView_Description {
            get {
                return ResourceManager.GetString("RegistrationView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt Anmelden.
        /// </summary>
        public static string RegistrationView_RegisterNow {
            get {

                return ResourceManager.GetString("RegistrationView_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt anmelden.
        /// </summary>
        public static string RegistrationView_RegisterUser {
            get {
                return ResourceManager.GetString("RegistrationView_RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string RegistrationView_UnRegisterUser {
            get {
                return ResourceManager.GetString("RegistrationView_UnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo Apollo.
        ///.
        /// </summary>
        public static string SettingsView_EmailBody {
            get {
                return ResourceManager.GetString("SettingsView_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anregungen oder Wunsch.
        /// </summary>
        public static string SettingsView_EmailSubject {
            get {
                return ResourceManager.GetString("SettingsView_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string SettingsView_Imprint {
            get {
                return ResourceManager.GetString("SettingsView_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.invite-apollo.app/Imprint.
        /// </summary>
        public static string SettingsView_ImprintUri {
            get {
                return ResourceManager.GetString("SettingsView_ImprintUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        public static string SettingsView_Privacy {
            get {
                return ResourceManager.GetString("SettingsView_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.invite-apollo.app/privacy.
        /// </summary>
        public static string SettingsView_PrivacyUri {
            get {
                return ResourceManager.GetString("SettingsView_PrivacyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilf uns die Zukunft der Bildung zu gestalten..
        /// </summary>
        public static string SettingsView_QuestionDescription {
            get {
                return ResourceManager.GetString("SettingsView_QuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to martin.mailman@lorem.de.
        /// </summary>
        public static string SettingsView_QuestionEmail {
            get {
                return ResourceManager.GetString("SettingsView_QuestionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anregungen oder Wünsche?.
        /// </summary>
        public static string SettingsView_Questions {
            get {
                return ResourceManager.GetString("SettingsView_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        public static string SettingsView_Terms {
            get {
                return ResourceManager.GetString("SettingsView_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.invite-apollo.app/terms.
        /// </summary>
        public static string SettingsView_TermsUri {
            get {
                return ResourceManager.GetString("SettingsView_TermsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwort wählen.
        /// </summary>
        public static string SkipQuestionDialog_Cancel {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        public static string SkipQuestionDialog_Continue {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jede Frage ist nur einmalig durchführbar und Antworten können nicht korrigiert werden.
        /// </summary>
        public static string SkipQuestionDialog_Message {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du dir sicher, dass du diese Frage überspringen möchtest?.
        /// </summary>
        public static string SkipQuestionDialog_Title {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usecase ändern.
        /// </summary>
        public static string StartView_ChangeUseCase {
            get {
                return ResourceManager.GetString("StartView_ChangeUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Ziel.
        /// </summary>
        public static string StartView_Goal {
            get {
                return ResourceManager.GetString("StartView_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobald du Inhalte favorisierst werden sie hier erscheinen..
        /// </summary>
        public static string StartView_NoFavoritesDescription {
            get {
                return ResourceManager.GetString("StartView_NoFavoritesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast noch keine Favoriten gesetzt.
        /// </summary>
        public static string StartView_NoFavoritesTitle {
            get {
                return ResourceManager.GetString("StartView_NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreiche deine Ziele.
        /// </summary>
        public static string StartViewModel_FavoritesHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_FavoritesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Favoriten.
        /// </summary>
        public static string StartViewModel_FavoritesSubline {
            get {
                return ResourceManager.GetString("StartViewModel_FavoritesSubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entdecke dein Karrierepotential
        ///(Ist-Stand bekannt – Inspiration).
        /// </summary>
        public static string StartViewModel_InteractionCareer {
            get {
                return ResourceManager.GetString("StartViewModel_InteractionCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobald du Inhalte favorisierst werden sie hier erscheinen..
        /// </summary>
        public static string StartViewModel_NoFavoritesText {
            get {
                return ResourceManager.GetString("StartViewModel_NoFavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast noch keine Favoriten gesetzt.
        /// </summary>
        public static string StartViewModel_NoFavoritesTitle {
            get {
                return ResourceManager.GetString("StartViewModel_NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empfohlene Inhalte.
        /// </summary>
        public static string StartViewModel_RecomondationsSubline {
            get {
                return ResourceManager.GetString("StartViewModel_RecomondationsSubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Anbieter.
        /// </summary>
        public static string StartViewModel_UnknownProvider {
            get {
                return ResourceManager.GetString("StartViewModel_UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhöhe deine Jobchancen.
        /// </summary>
        public static string StartViewModel_UseCaseA_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseA_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lerne neue Fähigkeiten.
        /// </summary>
        public static string StartViewModel_UseCaseB_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseB_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschleunige deinen Aufstieg.
        /// </summary>
        public static string StartViewModel_UseCaseC_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseC_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Szenario.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du möchtest einen sicheren Job finden.
        /// </summary>
        public static string UseCase_A_Description {
            get {
                return ResourceManager.GetString("UseCase_A_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitssuche.
        /// </summary>
        public static string UseCase_A_Name {
            get {
                return ResourceManager.GetString("UseCase_A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du möchtest neue Fähigkeiten erwerben.
        /// </summary>
        public static string UseCase_B_Description {
            get {
                return ResourceManager.GetString("UseCase_B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterbildung.
        /// </summary>
        public static string UseCase_B_Name {
            get {
                return ResourceManager.GetString("UseCase_B_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du möchtest in deinem Job Karriere machen.
        /// </summary>
        public static string UseCase_C_Description {
            get {
                return ResourceManager.GetString("UseCase_C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karriereaufstieg.
        /// </summary>
        public static string UseCase_C_Name {
            get {
                return ResourceManager.GetString("UseCase_C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter: {0}.
        /// </summary>
        public static string UseCaseDescriptionView_AgeFormat {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_AgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahrung.
        /// </summary>
        public static string UseCaseDescriptionView_Experience {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel.
        /// </summary>
        public static string UseCaseDescriptionView_Goal {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort: {0}.
        /// </summary>
        public static string UseCaseDescriptionView_LocationFormat {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_LocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szenario starten.
        /// </summary>
        public static string UseCaseDescriptionView_Start {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string UseCaseDescriptionView_Story {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Szenario.
        /// </summary>
        public static string UseCaseDescriptionView_Title {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string UseCaseDetail_A_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Jahre Helfer in Lager &amp; Versandt
        ///1 Jahr Einzelhandel mit Lebensmitteln.
        /// </summary>
        public static string UseCaseDetail_A_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job im Bereich Lager
        ///Langfristig stabilere Arbeitsbedingungen.
        /// </summary>
        public static string UseCaseDetail_A_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ludwigsburg.
        /// </summary>
        public static string UseCaseDetail_A_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast in den letzten vier Jahren in einem großen Versandlager gearbeitet. Deine Aufgabe war es, Waren aus dem Lager für Lieferaufträge zusammenzustellen. Vorher hast du eine Ausbildung im Einzelhandel angefangen, jedoch abgebrochen. Dein Unternehmen hat beschlossen, den Standort zu schließen. Du bist auf der Suche nach einem neuen Job im Bereich Lager..
        /// </summary>
        public static string UseCaseDetail_A_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string UseCaseDetail_B_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Jahre Ausbildung Kauffrau im Einzelhandel
        ///19 Jahre Erfahrung im Einzelhandel.
        /// </summary>
        public static string UseCaseDetail_B_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterbildung im Bereich E-Commerce
        ///Anschlussfähig bleiben und neue Bereiche entdecken.
        /// </summary>
        public static string UseCaseDetail_B_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to München.
        /// </summary>
        public static string UseCaseDetail_B_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du arbeitest seit 22 Jahren im Einzelhandel. Dein Betrieb hat in den letzten Jahren neben dem Geschäft vor Ort auch den Online-Handel weiter ausgebaut. Um anschlussfähig zu bleiben, möchtest du dich im Bereich E-Commerce weiterbilden..
        /// </summary>
        public static string UseCaseDetail_B_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string UseCaseDetail_C_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Jahre Ausbildung Fachinformatikerin
        ///1 Jahr Weiterbildung IHK Techniker IT
        ///10 Jahre Erfahrung Systemintegration.
        /// </summary>
        public static string UseCaseDetail_C_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufliche Weiterentwicklung
        ///Weiterbildung zur IT Projektleiterin.
        /// </summary>
        public static string UseCaseDetail_C_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augsburg.
        /// </summary>
        public static string UseCaseDetail_C_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCaseDetail_C_Story.
        /// </summary>
        public static string UseCaseDetail_C_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle dein Szenario.
        /// </summary>
        public static string UseCaseSelectionView_Choose {
            get {
                return ResourceManager.GetString("UseCaseSelectionView_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Inhalte der Beta passen sich an dein gewähltes Ziel an..
        /// </summary>
        public static string UseCaseSelectionView_ChooseDescription {
            get {
                return ResourceManager.GetString("UseCaseSelectionView_ChooseDescription", resourceCulture);
            }
        }
    }
}
