//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.HDBW.Apollo.Client.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("De.HDBW.Apollo.Client.Resources.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apollo liefert dir passgenaue Weiterbildungs- und Stellenangebote!.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dafür braucht Apollo Infos zu deinen beruflichen Erfahrungen von dir..
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsere App zeigt dir den Weg zu deinem Traumberuf!.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direkt loslegen.
        /// </summary>
        public static string FirstTimeDialog_Continue {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zum ersten mal hier?.
        /// </summary>
        public static string FirstTimeDialog_Message {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial anzeigen.
        /// </summary>
        public static string FirstTimeDialog_OpenTutorial {
            get {
                return ResourceManager.GetString("FirstTimeDialog_OpenTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen!.
        /// </summary>
        public static string FirstTimeDialog_Title {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        public static string Global_Skip {
            get {
                return ResourceManager.GetString("Global_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeugnisse und Abschlüsse.
        /// </summary>
        public static string MainNavigation_CertificatesAndDegrees {
            get {
                return ResourceManager.GetString("MainNavigation_CertificatesAndDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gemerkte Kurse.
        /// </summary>
        public static string MainNavigation_CoursesFavorites {
            get {
                return ResourceManager.GetString("MainNavigation_CoursesFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Generator.
        /// </summary>
        public static string MainNavigation_CVGenerator {
            get {
                return ResourceManager.GetString("MainNavigation_CVGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil bearbeiten.
        /// </summary>
        public static string MainNavigation_EditProfile {
            get {
                return ResourceManager.GetString("MainNavigation_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessenfelder.
        /// </summary>
        public static string MainNavigation_FieldsOfInterest {
            get {
                return ResourceManager.GetString("MainNavigation_FieldsOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lernpfad.
        /// </summary>
        public static string MainNavigation_LearningPath {
            get {
                return ResourceManager.GetString("MainNavigation_LearningPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen &amp; Filter.
        /// </summary>
        public static string MainNavigation_SettingsAndFilter {
            get {
                return ResourceManager.GetString("MainNavigation_SettingsAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills &amp; Badges.
        /// </summary>
        public static string MainNavigation_SkillsAndBadges {
            get {
                return ResourceManager.GetString("MainNavigation_SkillsAndBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial anzeigen.
        /// </summary>
        public static string MainNavigation_ViewTutorial {
            get {
                return ResourceManager.GetString("MainNavigation_ViewTutorial", resourceCulture);
            }
        }
    }
}
