//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.HDBW.Apollo.Client.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("De.HDBW.Apollo.Client.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Kann nur einmalig ausgeführt werden ähnelt.
        /// </summary>
        public static string AssessmentDescriptionView_OnlyOnce {
            get {
                return ResourceManager.GetString("AssessmentDescriptionView_OnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string AssessmentDescriptionView_Title {
            get {
                return ResourceManager.GetString("AssessmentDescriptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test starten* ähnelt.
        /// </summary>
        public static string AssessmentDescriptionViewModel_Skill_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_Skill_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test starten* ähnelt.
        /// </summary>
        public static string AssessmentDescriptionViewModel_SoftSkill_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_SoftSkill_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umfrage starten* ähnelt.
        /// </summary>
        public static string AssessmentDescriptionViewModel_Survey_Start {
            get {
                return ResourceManager.GetString("AssessmentDescriptionViewModel_Survey_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        /// </summary>
        public static string AssessmentItem_DecoratorText {
            get {
                return ResourceManager.GetString("AssessmentItem_DecoratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string AssessmentResultView_CloseAssessment {
            get {
                return ResourceManager.GetString("AssessmentResultView_CloseAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Rahmen der Testversion zeigen wir dir hier dein vorläufiges Ergebnis. Wie du im Vergleich zu anderen abschneidest, erfährst du in der finalen Version der App! ähnelt.
        /// </summary>
        public static string AssessmentResultView_Description {
            get {
                return ResourceManager.GetString("AssessmentResultView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Analyse ähnelt.
        /// </summary>
        public static string AssessmentResultView_Headline {
            get {
                return ResourceManager.GetString("AssessmentResultView_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfohlene Inhalte ähnelt.
        /// </summary>
        public static string AssessmentResultView_RecommendationDescription {
            get {
                return ResourceManager.GetString("AssessmentResultView_RecommendationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lerne neue Fähigkeiten ähnelt.
        /// </summary>
        public static string AssessmentResultView_RecommendationHeadline {
            get {
                return ResourceManager.GetString("AssessmentResultView_RecommendationHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswertung ähnelt.
        /// </summary>
        public static string AssessmentResultView_Title {
            get {
                return ResourceManager.GetString("AssessmentResultView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lückentext ähnelt.
        /// </summary>
        public static string AssessmentType_Cloze {
            get {
                return ResourceManager.GetString("AssessmentType_Cloze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfahrungen ähnelt.
        /// </summary>
        public static string AssessmentType_ExperienceAssessment {
            get {
                return ResourceManager.GetString("AssessmentType_ExperienceAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        /// </summary>
        public static string AssessmentType_SkillAssessment {
            get {
                return ResourceManager.GetString("AssessmentType_SkillAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selbsttest ähnelt.
        /// </summary>
        public static string AssessmentType_SoftSkillAssessment {
            get {
                return ResourceManager.GetString("AssessmentType_SoftSkillAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umfrage ähnelt.
        /// </summary>
        public static string AssessmentType_Survey {
            get {
                return ResourceManager.GetString("AssessmentType_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortfahren ähnelt.
        /// </summary>
        public static string CancelAssessmentDialog_Cancel {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test beenden ähnelt.
        /// </summary>
        public static string CancelAssessmentDialog_Continue {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tests sind nur einmalig durchführbar und können nicht wiederholt werden. ähnelt.
        /// </summary>
        public static string CancelAssessmentDialog_Message {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bist du dir sicher, dass du den Test beenden möchtest? ähnelt.
        /// </summary>
        public static string CancelAssessmentDialog_Title {
            get {
                return ResourceManager.GetString("CancelAssessmentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich stimme zu. ähnelt.
        /// </summary>
        public static string ConfirmDataUsageDialog_Agree {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string ConfirmDataUsageDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        public static string ConfirmDataUsageDialog_Continue {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit Ihrer Anmeldung stimmen Sie einer Kontaktaufnahme und Datenspeicherung für die Vorbereitung, Durchführung, Nachbereitung und Dokumentation der Beta zu. Die Anmeldung kann in den Einstellungen der App jeder Zeit wiederrufen werden. ähnelt.
        /// </summary>
        public static string ConfirmDataUsageDialog_Message {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir benötigen Ihre Zustimmung ähnelt.
        /// </summary>
        public static string ConfirmDataUsageDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmDataUsageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zulassung ähnelt.
        /// </summary>
        public static string CourseTagType_Admission {
            get {
                return ResourceManager.GetString("CourseTagType_Admission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teilnahmebescheinigung ähnelt.
        /// </summary>
        public static string CourseTagType_AttendeeCertificate {
            get {
                return ResourceManager.GetString("CourseTagType_AttendeeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zertifikat ähnelt.
        /// </summary>
        public static string CourseTagType_Certificate {
            get {
                return ResourceManager.GetString("CourseTagType_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiterbildung ähnelt.
        /// </summary>
        public static string CourseTagType_Course {
            get {
                return ResourceManager.GetString("CourseTagType_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veranstaltung ähnelt.
        /// </summary>
        public static string CourseTagType_InfoEvent {
            get {
                return ResourceManager.GetString("CourseTagType_InfoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teilqualifikation ähnelt.
        /// </summary>
        public static string CourseTagType_PartialQualification {
            get {
                return ResourceManager.GetString("CourseTagType_PartialQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Qualifikation ähnelt.
        /// </summary>
        public static string CourseTagType_Qualification {
            get {
                return ResourceManager.GetString("CourseTagType_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle ähnelt.
        /// </summary>
        public static string CourseType_All {
            get {
                return ResourceManager.GetString("CourseType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorort ähnelt.
        /// </summary>
        public static string CourseType_InHouse {
            get {
                return ResourceManager.GetString("CourseType_InHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persönlich ähnelt.
        /// </summary>
        public static string CourseType_InPerson {
            get {
                return ResourceManager.GetString("CourseType_InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online und Vorort ähnelt.
        /// </summary>
        public static string CourseType_OnAndOffline {
            get {
                return ResourceManager.GetString("CourseType_OnAndOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online ähnelt.
        /// </summary>
        public static string CourseType_Online {
            get {
                return ResourceManager.GetString("CourseType_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorteile ähnelt.
        /// </summary>
        public static string CourseView_Benefits {
            get {
                return ResourceManager.GetString("CourseView_Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansprechpartner ähnelt.
        /// </summary>
        public static string CourseView_Contact {
            get {
                return ResourceManager.GetString("CourseView_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ergebnis ähnelt.
        /// </summary>
        public static string CourseView_LearningOutcomes {
            get {
                return ResourceManager.GetString("CourseView_LearningOutcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finanzierungsoptionen anzeigen ähnelt.
        /// </summary>
        public static string CourseView_LoanOptions {
            get {
                return ResourceManager.GetString("CourseView_LoanOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voraussetzungen ähnelt.
        /// </summary>
        public static string CourseView_PreRequisites {
            get {
                return ResourceManager.GetString("CourseView_PreRequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ESCO-Skills ähnelt.
        /// </summary>
        public static string CourseView_Skills {
            get {
                return ResourceManager.GetString("CourseView_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zielgruppe ähnelt.
        /// </summary>
        public static string CourseView_TargetGroup {
            get {
                return ResourceManager.GetString("CourseView_TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursinformationen ähnelt.
        /// </summary>
        public static string CourseView_Title {
            get {
                return ResourceManager.GetString("CourseView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Anbieter ähnelt.
        /// </summary>
        public static string CourseView_VisitVendor {
            get {
                return ResourceManager.GetString("CourseView_VisitVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir unterstützen dich beim Erreichen deiner persönlichen Ziele durch passgenaue Lerninhalte ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entdecke passende Weiterbildungen ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction1Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction1Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erkenne Trends in deinem Berufsfeld und sei immer auf dem neuesten Stand ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halte dein Wissen aktuell ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction2Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction2Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teste dein Wissen und analysiere deine Fähigkeiten ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3 {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfalte dein Potential ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Instruction3Detail {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Instruction3Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen zur Beta von Apollo ähnelt.
        /// </summary>
        public static string ExtendedSplashScreenView_Welcome {
            get {
                return ResourceManager.GetString("ExtendedSplashScreenView_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://forms.office.com/e/cmES4qec8q ähnelt.
        /// </summary>
        public static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die individuelles Startdatum ähnelt.
        /// </summary>
        public static string FiltersSheet_IndividualStartDate {
            get {
                return ResourceManager.GetString("FiltersSheet_IndividualStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standort ähnelt.
        /// </summary>
        public static string FiltersSheet_Location {
            get {
                return ResourceManager.GetString("FiltersSheet_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis ähnelt.
        /// </summary>
        public static string FiltersSheet_Price {
            get {
                return ResourceManager.GetString("FiltersSheet_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relevanz aufsteigend ähnelt.
        /// </summary>
        public static string FiltersSheet_RelevanceAscending {
            get {
                return ResourceManager.GetString("FiltersSheet_RelevanceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relevanz absteigend ähnelt.
        /// </summary>
        public static string FiltersSheet_RelevanceDescending {
            get {
                return ResourceManager.GetString("FiltersSheet_RelevanceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis auswählen ähnelt.
        /// </summary>
        public static string FiltersSheet_SelectPrice {
            get {
                return ResourceManager.GetString("FiltersSheet_SelectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sortierung ähnelt.
        /// </summary>
        public static string FiltersSheet_Sorting {
            get {
                return ResourceManager.GetString("FiltersSheet_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die direkt loslegen ähnelt.
        /// </summary>
        public static string FirstTimeDialog_Continue {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zum ersten mal hier? ähnelt.
        /// </summary>
        public static string FirstTimeDialog_Message {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tutorial anzeigen ähnelt.
        /// </summary>
        public static string FirstTimeDialog_OpenTutorial {
            get {
                return ResourceManager.GetString("FirstTimeDialog_OpenTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen! ähnelt.
        /// </summary>
        public static string FirstTimeDialog_Title {
            get {
                return ResourceManager.GetString("FirstTimeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        public static string Global_Back {
            get {
                return ResourceManager.GetString("Global_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string Global_Close {
            get {
                return ResourceManager.GetString("Global_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Minuten ähnelt.
        /// </summary>
        public static string Global_DurationFormat {
            get {
                return ResourceManager.GetString("Global_DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Stunden ähnelt.
        /// </summary>
        public static string Global_DurationFormatHours {
            get {
                return ResourceManager.GetString("Global_DurationFormatHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        public static string Global_Next {
            get {
                return ResourceManager.GetString("Global_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überspringen ähnelt.
        /// </summary>
        public static string Global_Skip {
            get {
                return ResourceManager.GetString("Global_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt starten ähnelt.
        /// </summary>
        public static string Global_StartNow {
            get {
                return ResourceManager.GetString("Global_StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trifft garnicht zu ähnelt.
        /// </summary>
        public static string IntegerInput_Negative {
            get {
                return ResourceManager.GetString("IntegerInput_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trifft voll zu ähnelt.
        /// </summary>
        public static string IntegerInput_Positive {
            get {
                return ResourceManager.GetString("IntegerInput_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zukünftig werden dir hier weitere Funktionen zur Verfügung stehen ähnelt.
        /// </summary>
        public static string MainNavigation_BetaDescription {
            get {
                return ResourceManager.GetString("MainNavigation_BetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beta Version ähnelt.
        /// </summary>
        public static string MainNavigation_BetaTitle {
            get {
                return ResourceManager.GetString("MainNavigation_BetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeugnisse und Abschlüsse ähnelt.
        /// </summary>
        public static string MainNavigation_CertificatesAndDegrees {
            get {
                return ResourceManager.GetString("MainNavigation_CertificatesAndDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Szenario wechseln ähnelt.
        /// </summary>
        public static string MainNavigation_ChangeUseCase {
            get {
                return ResourceManager.GetString("MainNavigation_ChangeUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gemerkte Kurse ähnelt.
        /// </summary>
        public static string MainNavigation_CoursesFavorites {
            get {
                return ResourceManager.GetString("MainNavigation_CoursesFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CV Generator ähnelt.
        /// </summary>
        public static string MainNavigation_CVGenerator {
            get {
                return ResourceManager.GetString("MainNavigation_CVGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profil bearbeiten ähnelt.
        /// </summary>
        public static string MainNavigation_EditProfile {
            get {
                return ResourceManager.GetString("MainNavigation_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback senden ähnelt.
        /// </summary>
        public static string MainNavigation_Feedback {
            get {
                return ResourceManager.GetString("MainNavigation_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interessenfelder ähnelt.
        /// </summary>
        public static string MainNavigation_FieldsOfInterest {
            get {
                return ResourceManager.GetString("MainNavigation_FieldsOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lernpfad ähnelt.
        /// </summary>
        public static string MainNavigation_LearningPath {
            get {
                return ResourceManager.GetString("MainNavigation_LearningPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string MainNavigation_Settings {
            get {
                return ResourceManager.GetString("MainNavigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen &amp; Filter ähnelt.
        /// </summary>
        public static string MainNavigation_SettingsAndFilter {
            get {
                return ResourceManager.GetString("MainNavigation_SettingsAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skills &amp; Badges ähnelt.
        /// </summary>
        public static string MainNavigation_SkillsAndBadges {
            get {
                return ResourceManager.GetString("MainNavigation_SkillsAndBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tutorial anzeigen ähnelt.
        /// </summary>
        public static string MainNavigation_ViewTutorial {
            get {
                return ResourceManager.GetString("MainNavigation_ViewTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollzeit ähnelt.
        /// </summary>
        public static string OccurrenceType_FullTime {
            get {
                return ResourceManager.GetString("OccurrenceType_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voll- und Teilzeit ähnelt.
        /// </summary>
        public static string OccurrenceType_FullTimeAndPartTime {
            get {
                return ResourceManager.GetString("OccurrenceType_FullTimeAndPartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teilzeit ähnelt.
        /// </summary>
        public static string OccurrenceType_PartTime {
            get {
                return ResourceManager.GetString("OccurrenceType_PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enddatum ähnelt.
        /// </summary>
        public static string PropertyEditor_EndDate {
            get {
                return ResourceManager.GetString("PropertyEditor_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startdatum ähnelt.
        /// </summary>
        public static string PropertyEditor_StartDate {
            get {
                return ResourceManager.GetString("PropertyEditor_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ohne Anmeldung fortfahren ähnelt.
        /// </summary>
        public static string RegistrationView_Continue {
            get {
                return ResourceManager.GetString("RegistrationView_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Während der Testung benötigst Du keine Registrierung/Anmeldung. Wenn Du Dich allerdings für zukünftige Testversionen registrieren möchtest, kannst Du das über &quot;Jetzt anmelden&quot; vornehmen. Solltest Du Deine Meinung ändern, kannst Du über Einstellungen → &quot;Benutzer abmelden&quot; die Registrierung/Anmeldung löschen. ähnelt.
        /// </summary>
        public static string RegistrationView_Description {
            get {
                return ResourceManager.GetString("RegistrationView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt Anmelden ähnelt.
        /// </summary>
        public static string RegistrationView_RegisterNow {
            get {
                return ResourceManager.GetString("RegistrationView_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt anmelden ähnelt.
        /// </summary>
        public static string RegistrationView_RegisterUser {
            get {
                return ResourceManager.GetString("RegistrationView_RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        public static string RegistrationView_UnRegisterUser {
            get {
                return ResourceManager.GetString("RegistrationView_UnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string SearchView_Title {
            get {
                return ResourceManager.GetString("SearchView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo Apollo-Team.
        /// ähnelt.
        /// </summary>
        public static string SettingsView_EmailBody {
            get {
                return ResourceManager.GetString("SettingsView_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anregungen oder Wunsch zu Apollo ähnelt.
        /// </summary>
        public static string SettingsView_EmailSubject {
            get {
                return ResourceManager.GetString("SettingsView_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        public static string SettingsView_Imprint {
            get {
                return ResourceManager.GetString("SettingsView_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.invite-apollo.app/Imprint ähnelt.
        /// </summary>
        public static string SettingsView_ImprintUri {
            get {
                return ResourceManager.GetString("SettingsView_ImprintUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenschutz ähnelt.
        /// </summary>
        public static string SettingsView_Privacy {
            get {
                return ResourceManager.GetString("SettingsView_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.invite-apollo.app/privacy ähnelt.
        /// </summary>
        public static string SettingsView_PrivacyUri {
            get {
                return ResourceManager.GetString("SettingsView_PrivacyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilf uns die Zukunft der Bildung zu gestalten. ähnelt.
        /// </summary>
        public static string SettingsView_QuestionDescription {
            get {
                return ResourceManager.GetString("SettingsView_QuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die apollodev@hdbw-hochschule.de ähnelt.
        /// </summary>
        public static string SettingsView_QuestionEmail {
            get {
                return ResourceManager.GetString("SettingsView_QuestionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anregungen oder Wünsche? ähnelt.
        /// </summary>
        public static string SettingsView_Questions {
            get {
                return ResourceManager.GetString("SettingsView_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nutzungsbedingungen ähnelt.
        /// </summary>
        public static string SettingsView_Terms {
            get {
                return ResourceManager.GetString("SettingsView_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.invite-apollo.app/terms ähnelt.
        /// </summary>
        public static string SettingsView_TermsUri {
            get {
                return ResourceManager.GetString("SettingsView_TermsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antwort wählen ähnelt.
        /// </summary>
        public static string SkipQuestionDialog_Cancel {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überspringen ähnelt.
        /// </summary>
        public static string SkipQuestionDialog_Continue {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jede Frage ist nur einmalig durchführbar und Antworten können nicht korrigiert werden ähnelt.
        /// </summary>
        public static string SkipQuestionDialog_Message {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bist du dir sicher, dass du diese Frage überspringen möchtest? ähnelt.
        /// </summary>
        public static string SkipQuestionDialog_Title {
            get {
                return ResourceManager.GetString("SkipQuestionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usecase ändern ähnelt.
        /// </summary>
        public static string StartView_ChangeUseCase {
            get {
                return ResourceManager.GetString("StartView_ChangeUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mein Ziel ähnelt.
        /// </summary>
        public static string StartView_Goal {
            get {
                return ResourceManager.GetString("StartView_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sobald du Inhalte favorisierst werden sie hier erscheinen. ähnelt.
        /// </summary>
        public static string StartView_NoFavoritesDescription {
            get {
                return ResourceManager.GetString("StartView_NoFavoritesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast noch keine Favoriten gesetzt ähnelt.
        /// </summary>
        public static string StartView_NoFavoritesTitle {
            get {
                return ResourceManager.GetString("StartView_NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erreiche deine Ziele ähnelt.
        /// </summary>
        public static string StartViewModel_FavoritesHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_FavoritesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Favoriten ähnelt.
        /// </summary>
        public static string StartViewModel_FavoritesSubline {
            get {
                return ResourceManager.GetString("StartViewModel_FavoritesSubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entdecke dein Karrierepotential
        ///(Ist-Stand bekannt – Inspiration) ähnelt.
        /// </summary>
        public static string StartViewModel_InteractionCareer {
            get {
                return ResourceManager.GetString("StartViewModel_InteractionCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sobald du Inhalte favorisierst werden sie hier erscheinen. ähnelt.
        /// </summary>
        public static string StartViewModel_NoFavoritesText {
            get {
                return ResourceManager.GetString("StartViewModel_NoFavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast noch keine Favoriten gesetzt ähnelt.
        /// </summary>
        public static string StartViewModel_NoFavoritesTitle {
            get {
                return ResourceManager.GetString("StartViewModel_NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfohlene Inhalte ähnelt.
        /// </summary>
        public static string StartViewModel_RecomondationsSubline {
            get {
                return ResourceManager.GetString("StartViewModel_RecomondationsSubline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Anbieter ähnelt.
        /// </summary>
        public static string StartViewModel_UnknownProvider {
            get {
                return ResourceManager.GetString("StartViewModel_UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erhöhe deine Jobchancen ähnelt.
        /// </summary>
        public static string StartViewModel_UseCaseA_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseA_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lerne neue Fähigkeiten ähnelt.
        /// </summary>
        public static string StartViewModel_UseCaseB_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseB_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschleunige deinen Aufstieg ähnelt.
        /// </summary>
        public static string StartViewModel_UseCaseC_RecomondationsHeadline {
            get {
                return ResourceManager.GetString("StartViewModel_UseCaseC_RecomondationsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dein Szenario ähnelt.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du möchtest dich auf einen sicheren Job vorbereiten ähnelt.
        /// </summary>
        public static string UseCase_A_Description {
            get {
                return ResourceManager.GetString("UseCase_A_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fit für den Job ähnelt.
        /// </summary>
        public static string UseCase_A_Name {
            get {
                return ResourceManager.GetString("UseCase_A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du möchtest neue Fähigkeiten erwerben ähnelt.
        /// </summary>
        public static string UseCase_B_Description {
            get {
                return ResourceManager.GetString("UseCase_B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiterbildung ähnelt.
        /// </summary>
        public static string UseCase_B_Name {
            get {
                return ResourceManager.GetString("UseCase_B_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du möchtest in deinem Job Karriere machen ähnelt.
        /// </summary>
        public static string UseCase_C_Description {
            get {
                return ResourceManager.GetString("UseCase_C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karriereaufstieg ähnelt.
        /// </summary>
        public static string UseCase_C_Name {
            get {
                return ResourceManager.GetString("UseCase_C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finde passende Kurse für deine Interessen ähnelt.
        /// </summary>
        public static string UseCase_D_Description {
            get {
                return ResourceManager.GetString("UseCase_D_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string UseCase_D_Name {
            get {
                return ResourceManager.GetString("UseCase_D_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alter: {0} ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_AgeFormat {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_AgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfahrung ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_Experience {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ziel ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_Goal {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort: {0} ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_LocationFormat {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_LocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Szenario starten ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_Start {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Story ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_Story {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dein Szenario ähnelt.
        /// </summary>
        public static string UseCaseDescriptionView_Title {
            get {
                return ResourceManager.GetString("UseCaseDescriptionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 31 ähnelt.
        /// </summary>
        public static string UseCaseDetail_A_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 Jahre Lager und Kommissionierung
        ///1 Jahr Einzelhandel im Lebensmittelbereich ähnelt.
        /// </summary>
        public static string UseCaseDetail_A_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job im Bereich Lager
        ///Langfristig stabilere Arbeitsbedingungen ähnelt.
        /// </summary>
        public static string UseCaseDetail_A_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ludwigsburg ähnelt.
        /// </summary>
        public static string UseCaseDetail_A_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast in den letzten vier Jahren in einem großen Versandlager gearbeitet. Deine Aufgabe war es, Waren aus dem Lager für Lieferaufträge zusammenzustellen. Vorher hast du eine Ausbildung im Einzelhandel angefangen, jedoch abgebrochen. Dein Unternehmen hat beschlossen, den Standort zu schließen. Du bist auf der Suche nach einem neuen Job im Bereich Lager. ähnelt.
        /// </summary>
        public static string UseCaseDetail_A_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_A_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 42 ähnelt.
        /// </summary>
        public static string UseCaseDetail_B_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 Jahre Ausbildung Kauffrau im Einzelhandel
        ///19 Jahre Erfahrung im Einzelhandel ähnelt.
        /// </summary>
        public static string UseCaseDetail_B_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiterbildung im Bereich E-Commerce
        ///Anschlussfähig bleiben und neue Bereiche entdecken ähnelt.
        /// </summary>
        public static string UseCaseDetail_B_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die München ähnelt.
        /// </summary>
        public static string UseCaseDetail_B_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du arbeitest seit 22 Jahren im Einzelhandel. Dein Betrieb hat in den letzten Jahren neben dem Geschäft vor Ort auch den Online-Handel weiter ausgebaut. Um anschlussfähig zu bleiben, möchtest du dich im Bereich E-Commerce weiterbilden. ähnelt.
        /// </summary>
        public static string UseCaseDetail_B_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_B_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 36 ähnelt.
        /// </summary>
        public static string UseCaseDetail_C_Age {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 Jahre Ausbildung Fachinformatikerin
        ///1 Jahr Weiterbildung IHK Techniker IT
        ///10 Jahre Erfahrung Systemintegration ähnelt.
        /// </summary>
        public static string UseCaseDetail_C_Experience {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berufliche Weiterentwicklung
        ///Weiterbildung zur IT Projektleiterin ähnelt.
        /// </summary>
        public static string UseCaseDetail_C_Goal {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Augsburg ähnelt.
        /// </summary>
        public static string UseCaseDetail_C_Location {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast zehn Jahre Erfahrung als Fachinformatikerin. Neben deiner Arbeit hast du verschiedene Möglichkeiten wahrgenommen, um dich weiterzubilden und auf dem Laufenden zu bleiben. Nun willst du den nächsten Schritt in deiner Karriere gehen. Du bist auf der Suche nach einer Qualifizierung, um eine Führungsposition zu übernehmen. ähnelt.
        /// </summary>
        public static string UseCaseDetail_C_Story {
            get {
                return ResourceManager.GetString("UseCaseDetail_C_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle Deinen Testbereich ähnelt.
        /// </summary>
        public static string UseCaseSelectionView_Choose {
            get {
                return ResourceManager.GetString("UseCaseSelectionView_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die APOLLO befindet sich noch in der Testphase. Deine Teilnahme hilft uns die App weiterzuentwickeln. ähnelt.
        /// </summary>
        public static string UseCaseSelectionView_ChooseDescription {
            get {
                return ResourceManager.GetString("UseCaseSelectionView_ChooseDescription", resourceCulture);
            }
        }
    }
}
