// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace De.HDBW.Apollo.SharedContracts.Models
{
    public class Audio
    {
        public string name { get; set; }

        public string id { get; set; }

        public bool translatable { get; set; }
    }
}
