// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
// ------------------------------------------------------------------------------

using De.HDBW.Apollo.SharedContracts.Enums;
using De.HDBW.Apollo.SharedContracts.Models;

namespace De.HDBW.Apollo.SharedContracts
{
    public class RawData
    {
        public QuestionType type { get; set; }
        public string bezeichnung { get; set; }
        public string noprimary { get; set; }
        public string choice { get; set; }
        public string eacond_credit1 { get; set; }
        public string eacond_credit2 { get; set; }
        public Reliants? reliant { get; set; }
        public string verbis { get; set; }
        public string idesco { get; set; }
        public string handlungsfeld { get; set; }
        public Image bild1 { get; set; }
        public Image bild2 { get; set; }
        public Image bild3 { get; set; }
        public Image bild4 { get; set; }
        public string beispielberufe { get; set; }
        public string voraussetzungen { get; set; }
        public string infotext { get; set; }
        public string stemm { get; set; }
        public string substemm { get; set; }
        public string instruction { get; set; }
        public string primdistractor1 { get; set; }
        public string primdistractor2 { get; set; }
        public string primdistractor3 { get; set; }
        public string m_choice_option1_1 { get; set; }
        public string m_choice_option1_2 { get; set; }
        public string m_choice_option1_3 { get; set; }
        public string m_choice_credit1 { get; set; }
        public string m_choice_option2_1 { get; set; }
        public string m_choice_option2_2 { get; set; }
        public string m_choice_option2_3 { get; set; }
        public string m_choice_credit2 { get; set; }
        public string m_choice_option3_1 { get; set; }
        public string m_choice_option3_2 { get; set; }
        public string m_choice_option3_3 { get; set; }
        public string m_choice_credit3 { get; set; }
        public string binary_credit2 { get; set; }
        public Audio audio { get; set; }
        public string binary_credit1 { get; set; }
        public string picture_wide { get; set; }
        public string m_choice_option1_4 { get; set; }
        public string m_choice_option2_4 { get; set; }
        public string m_choice_option3_4 { get; set; }
        public string m_choice_option4_1 { get; set; }
        public string m_choice_option4_2 { get; set; }
        public string m_choice_option4_3 { get; set; }
        public string m_choice_option4_4 { get; set; }
        public string m_choice_credit4 { get; set; }
        public Image primimage1 { get; set; }
        public Image primimage2 { get; set; }
        public Image primimage3 { get; set; }
        public Image primimage4 { get; set; }
        public string primdistractor4 { get; set; }
        public string cloze { get; set; }
        public string show_primary { get; set; }
        public string cloze_scoringid1_1 { get; set; }
        public string cloze_scoringid1_2 { get; set; }
        public string cloze_scoringid1_3 { get; set; }
        public string cloze_scoringid1_4 { get; set; }
        public string cloze_scoringid2_1 { get; set; }
        public string cloze_scoringid2_2 { get; set; }
        public string cloze_scoringid2_3 { get; set; }
        public string cloze_scoringid2_4 { get; set; }
        public string cloze_scoringid3_1 { get; set; }
        public string cloze_scoringid3_2 { get; set; }
        public string cloze_scoringid3_3 { get; set; }
        public string cloze_scoringid3_4 { get; set; }
        public string cloze_scoringid4_1 { get; set; }
        public string cloze_scoringid4_2 { get; set; }
        public string cloze_scoringid4_3 { get; set; }
        public string cloze_scoringid4_4 { get; set; }
        public string cloze_id1_1 { get; set; }
        public string cloze_id1_2 { get; set; }
        public string cloze_id1_3 { get; set; }
        public string cloze_id1_4 { get; set; }
        public string cloze_id2_1 { get; set; }
        public string cloze_id2_2 { get; set; }
        public string cloze_id2_3 { get; set; }
        public string cloze_id2_4 { get; set; }
        public string cloze_id3_1 { get; set; }
        public string cloze_id3_2 { get; set; }
        public string cloze_id3_3 { get; set; }
        public string cloze_id3_4 { get; set; }
        public string cloze_id4_1 { get; set; }
        public string cloze_id4_2 { get; set; }
        public string cloze_id4_3 { get; set; }
        public string cloze_id4_4 { get; set; }
        public string cloze_credit1 { get; set; }
        public string cloze_credit2 { get; set; }
        public string cloze_credit3 { get; set; }
        public string cloze_credit4 { get; set; }
        public string job { get; set; }
        public string kldb { get; set; }
        public string schwerpunkt { get; set; }
        public string situation { get; set; }
        public string sort_option1_1 { get; set; }
        public string sort_option1_2 { get; set; }
        public string sort_option1_3 { get; set; }
        public string sort_option1_4 { get; set; }
        public string sort_option2_1 { get; set; }
        public string sort_option2_2 { get; set; }
        public string sort_option2_3 { get; set; }
        public string sort_option2_4 { get; set; }
        public string sort_option3_1 { get; set; }
        public string sort_option3_2 { get; set; }
        public string sort_option3_3 { get; set; }
        public string sort_option3_4 { get; set; }
        public string sort_credit1 { get; set; }
        public string sort_credit2 { get; set; }
        public string sort_credit3 { get; set; }
        public string nosecondary { get; set; }
        public string secdistractor1 { get; set; }
        public string secdistractor2 { get; set; }
        public string secdistractor3 { get; set; }
        public string secdistractor4 { get; set; }
        public string associate_option1_1 { get; set; }
        public string associate_option1_2 { get; set; }
        public string associate_option1_3 { get; set; }
        public string associate_option1_4 { get; set; }
        public string associate_credit1 { get; set; }
        public Image image { get; set; }
        public string coordinates1 { get; set; }
        public ShapeType form1 { get; set; }
        public string coordinates2 { get; set; }
        public ShapeType form2 { get; set; }
        public string coordinates3 { get; set; }
        public ShapeType form3 { get; set; }
        public string coordinates4 { get; set; }
        public ShapeType form4 { get; set; }
        public string m_imagemap_option1_1 { get; set; }
        public string m_imagemap_option1_2 { get; set; }
        public string m_imagemap_option1_3 { get; set; }
        public string m_imagemap_option1_4 { get; set; }
        public string m_imagemap_credit1 { get; set; }
        public string credit_1 { get; set; }
        public string credit_2 { get; set; }
        public string credit_3 { get; set; }
        public string m_imagemap_option2_1 { get; set; }
        public string m_imagemap_option2_2 { get; set; }
        public string m_imagemap_option2_3 { get; set; }
        public string m_imagemap_option2_4 { get; set; }
        public string m_imagemap_credit2 { get; set; }
        public string m_imagemap_option3_1 { get; set; }
        public string m_imagemap_option3_2 { get; set; }
        public string m_imagemap_option3_3 { get; set; }
        public string m_imagemap_option3_4 { get; set; }
        public string m_imagemap_credit3 { get; set; }
        public string m_imagemap_option4_1 { get; set; }
        public string m_imagemap_option4_2 { get; set; }
        public string m_imagemap_option4_3 { get; set; }
        public string m_imagemap_option4_4 { get; set; }
        public string m_imagemap_credit4 { get; set; }
        public Image secimage1 { get; set; }
        public Image secimage2 { get; set; }
        public Image secimage3 { get; set; }
        public Image secimage4 { get; set; }
        public string Choice_Ce { get; set; }
        public string frequency_credit1 { get; set; }
        public string frequency_credit2 { get; set; }
        public string frequency_credit3 { get; set; }
        public string frequency_credit4 { get; set; }
        public string module { get; set; }
        public string esco { get; set; }
        public string rating_credit1 { get; set; }
        public string rating_credit2 { get; set; }
        public string rating_credit3 { get; set; }
        public string rating_credit4 { get; set; }
        public string rating_credit5 { get; set; }
        public string rating_credit6 { get; set; }
    }

    public class Reliants
    {
        public Reliant reliant_0 { get; set; }
        public Reliant reliant_1 { get; set; }
        public Reliant reliant_2 { get; set; }
        public Reliant reliant_3 { get; set; }
        public Reliant reliant_4 { get; set; }
        public Reliant reliant_5 { get; set; }
        public Reliant reliant_6 { get; set; }
        public Reliant reliant_7 { get; set; }
        public Reliant reliant_8 { get; set; }
        public Reliant reliant_9 { get; set; }
        public Reliant reliant_10 { get; set; }
    }

    public class Reliant
    {
        public string id { get; set; }
        public string name { get; set; }
    }
}
