# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy

permissions:
  contents: read

jobs:
  deploy:
    runs-on:  macos-12
    name: Deploy
    needs: [build]
    steps:
      - name: Download Android build
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: android.yml
          workflow_conclusion: success
          branch: development
          path: artifact/android
      - name: Download iOS build
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ios.yml
          workflow_conclusion: success
          branch: development
          path: artifact/iOS
      - name: Deploy to PlayConsole
        if: always()
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: "${{secrets.SERVICE_ACCOUNT_JSON }}"
          packageName: de.hdbw.apollo.client
          releaseFiles: artifact/android/de.hdbw.apollo.client-Signed.aab
          track: internal
          status: completed
          inAppUpdatePriority: 0
      - name: Deploy to TestFlight
        if: always()
        uses: r0adkll/upload-testflight-build@v1
        with:
          app-path: 'artifact/iOS/publish/De.HDBW.Apollo.Client.ipa' 
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

