# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deployments
on:
  workflow_dispatch:
    inputs:
      deployAndroid:
        required: true
        default: "true"
      deployIOs:
        required: true
        default: "true"

permissions:
  contents: read

jobs:
  deployAndroid:
    runs-on: macos-12
    if: ${{ github.event.inputs.deployAndroid == 'true' }}
    name: Deploy Android
    steps:
      - name: Download Android artefacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITNUGET}}
          workflow: android.yml
          workflow_conclusion: success
          branch: development
          path: artifact
      - name: Deploy to PlayConsole
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: "${{secrets.SERVICE_ACCOUNT_JSON }}"
          packageName: de.hdbw.apollo.client
          releaseFiles: artifact/apollo-android-app/de.hdbw.apollo.client-Signed.aab
          track: internal
          status: completed
          inAppUpdatePriority: 0
  deployIOs:
      runs-on: macos-12
      if: ${{ github.event.inputs.deployIOs == 'true' }}
      name: Deploy Android
      steps:
      - name: Download iOS artefacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITNUGET}}
          workflow: ios.yml
          workflow_conclusion: success
          branch: development
          path: artifact
 
      - name: Deploy to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'artifact/apollo-ios-app/publish/De.HDBW.Apollo.Client.ipa' 
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
