# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: iOS Build

on:
  push:
    branches: [ "development" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
      - 'src/cloud/**'
  pull_request:
    branches: [ "development" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
      - 'src/cloud/**'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    - name: Init User-Secrets
      run: |
        echo ${{ github.workspace }}
        ENCODED_SWAGGER_API_TOKEN=${{secrets.SWAGGERAPIKEYBASE64}}
        DECODED_SWAGGER_API_TOKEN=$(echo "$ENCODED_SWAGGER_API_TOKEN" | base64 --decode)
        dotnet user-secrets init -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "ClientId" "${{secrets.B2CCLIENTID}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "TenantName" "${{secrets.B2CTENANTNAME}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "SignInPolicy" "${{secrets.SIGNINGPOLICY}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "InstrumentationKey" "${{secrets.APPI_INSTUMENTATION_KEY}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "SwaggerAPIToken" "$DECODED_SWAGGER_API_TOKEN" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "SwaggerAPIURL" "${{secrets.SWAGGERENDPOINTURL}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "OccupationSearchAPIURL" "${{secrets.OCCUPATIONSEARCHAPIURL}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
        dotnet user-secrets set "UnRegisteUserEndpointURL" "${{secrets.UNREGISTERUSERENDPOINTURL}}" -p src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 -d -o $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 -d -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
    - name: Set XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup nuget
      run: dotnet nuget add source -u patbosc -p ${{ secrets.GITNUGET }} --store-password-in-clear-text -n github "https://nuget.pkg.github.com/HDBW/index.json"
    - name: Restore dependencies
      run: dotnet restore src/client/Maui/Apollo.sln
    - name: Build MAUI iOS
      run: dotnet publish src/client/Maui/UI/De.HDBW.Apollo.Client/De.HDBW.Apollo.Client.csproj -f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:CodesignKey="${{secrets.CODESIGNINGKEY}}" /p:CodesignProvision=StoreProfile /p:CodesignEntitlements=${{github.workspace}}/src/client/Maui/UI/De.HDBW.Apollo.Client/Platforms/iOS/Entitlements.plist -v diag
    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: apollo-ios-app
        path: |
          src/client/Maui/UI/De.HDBW.Apollo.Client/bin/Release/net8.0-ios/ios-arm64/publish/*.ipa
          src/client/Maui/UI/De.HDBW.Apollo.Client/bin/Release/net8.0-ios/ios-arm64/**/*.dSYM
    - name: Cleanup
      if: always()
      run: dotnet nuget remove source github
